stages:
  - build

build:
  tags:
    - kubernetes
  stage: build
  image: cimg/openjdk:21.0
  script:
    - gradle build
  artifacts:
    name: "JARs"
    paths:
      - build/libs/*.jar
    expire_in: 7 days