auto-update: true
command:
  backpack:
    enabled: true
    slots: 27

bingo:
  maxItems: 9
  countdownHighestCountWin: true
  invalidItems:
    - ACACIA_WALL_HANGING_SIGN
    - ACACIA_WALL_SIGN
    - AIR
    - ALLAY_SPAWN_EGG
    - ARMADILLO_SPAWN_EGG
    - ATTACHED_MELON_STEM
    - ATTACHED_PUMPKIN_STEM
    - AXOLOTL_SPAWN_EGG
    - BAMBOO_SAPLING
    - BAMBOO_WALL_HANGING_SIGN
    - BAMBOO_WALL_SIGN
    - BARRIER
    - BAT_SPAWN_EGG
    - BEDROCK
    - BEE_SPAWN_EGG
    - BEETROOTS
    - BIG_DRIPLEAF_STEM
    - BIRCH_WALL_HANGING_SIGN
    - BIRCH_WALL_SIGN
    - BLACK_CANDLE_CAKE
    - BLACK_WALL_BANNER
    - BLAZE_SPAWN_EGG
    - BLUE_CANDLE_CAKE
    - BLUE_WALL_BANNER
    - BOGGED_SPAWN_EGG
    - BOLT_ARMOR_TRIM_SMITHING_TEMPLATE
    - BRAIN_CORAL_WALL_FAN
    - BREEZE_SPAWN_EGG
    - BROWN_CANDLE_CAKE
    - BROWN_WALL_BANNER
    - BUBBLE_COLUMN
    - BUBBLE_CORAL_WALL_FAN
    - BUNDLE
    - CAMEL_SPAWN_EGG
    - CANDLE_CAKE
    - CARROTS
    - CAT_SPAWN_EGG
    - CAVE_AIR
    - CAVE_SPIDER_SPAWN_EGG
    - CAVE_VINES
    - CAVE_VINES_PLANT
    - CHAIN_COMMAND_BLOCK
    - CHERRY_WALL_HANGING_SIGN
    - CHERRY_WALL_SIGN
    - CHICKEN_SPAWN_EGG
    - CHORUS_PLANT
    - COCOA
    - COD_SPAWN_EGG
    - COMMAND_BLOCK
    - COMMAND_BLOCK_MINECART
    - COPPER_BULB
    - COPPER_GRATE
    - COW_SPAWN_EGG
    - CRAFTER
    - CREEPER_SPAWN_EGG
    - CREEPER_WALL_HEAD
    - CRIMSON_WALL_HANGING_SIGN
    - CRIMSON_WALL_SIGN
    - CYAN_CANDLE_CAKE
    - CYAN_WALL_BANNER
    - DARK_OAK_WALL_HANGING_SIGN
    - DARK_OAK_WALL_SIGN
    - DEAD_BRAIN_CORAL_WALL_FAN
    - DEAD_BUBBLE_CORAL_WALL_FAN
    - DEAD_BUSH
    - DEAD_FIRE_CORAL_WALL_FAN
    - DEAD_HORN_CORAL_WALL_FAN
    - DEAD_TUBE_CORAL_WALL_FAN
    - DEBUG_STICK
    - DIRT_PATH
    - DOLPHIN_SPAWN_EGG
    - DONKEY_SPAWN_EGG
    - DRAGON_WALL_HEAD
    - DROWNED_SPAWN_EGG
    - ELDER_GUARDIAN_SPAWN_EGG
    - ENCHANTED_BOOK
    - END_GATEWAY
    - END_PORTAL
    - END_PORTAL_FRAME
    - ENDER_DRAGON_SPAWN_EGG
    - ENDERMAN_SPAWN_EGG
    - ENDERMITE_SPAWN_EGG
    - EVOKER_SPAWN_EGG
    - EXPOSED_CHISELED_COPPER
    - EXPOSED_COPPER_BULB
    - EXPOSED_COPPER_DOOR
    - EXPOSED_COPPER_GRATE
    - EXPOSED_COPPER_TRAPDOOR
    - FARMLAND
    - FILLED_MAP
    - FIRE
    - FIRE_CORAL_WALL_FAN
    - FIREWORK_ROCKET
    - FOX_SPAWN_EGG
    - FROG_SPAWN_EGG
    - FROSTED_ICE
    - GHAST_SPAWN_EGG
    - GLOW_SQUID_SPAWN_EGG
    - GOAT_SPAWN_EGG
    - GRAY_CANDLE_CAKE
    - GRAY_WALL_BANNER
    - GREEN_CANDLE_CAKE
    - GREEN_WALL_BANNER
    - GUARDIAN_SPAWN_EGG
    - HANGING_ROOTS
    - HEAVY_CORE
    - HOGLIN_SPAWN_EGG
    - HORN_CORAL_WALL_FAN
    - HORSE_SPAWN_EGG
    - HUSK_SPAWN_EGG
    - INFESTED_CHISELED_STONE_BRICKS
    - INFESTED_COBBLESTONE
    - INFESTED_CRACKED_STONE_BRICKS
    - INFESTED_DEEPSLATE
    - INFESTED_MOSSY_STONE_BRICKS
    - INFESTED_STONE
    - INFESTED_STONE_BRICKS
    - IRON_GOLEM_SPAWN_EGG
    - JIGSAW
    - JUNGLE_WALL_HANGING_SIGN
    - JUNGLE_WALL_SIGN
    - KELP_PLANT
    - KNOWLEDGE_BOOK
    - LARGE_FERN
    - LAVA
    - LAVA_CAULDRON
    - LIGHT
    - LIGHT_BLUE_CANDLE_CAKE
    - LIGHT_BLUE_WALL_BANNER
    - LIGHT_GRAY_CANDLE_CAKE
    - LIGHT_GRAY_WALL_BANNER
    - LIME_CANDLE_CAKE
    - LIME_WALL_BANNER
    - LINGERING_POTION
    - LLAMA_SPAWN_EGG
    - MACE
    - MAGENTA_CANDLE_CAKE
    - MAGENTA_WALL_BANNER
    - MAGMA_CUBE_SPAWN_EGG
    - MANGROVE_WALL_HANGING_SIGN
    - MANGROVE_WALL_SIGN
    - MELON_STEM
    - MOOSHROOM_SPAWN_EGG
    - MOVING_PISTON
    - MUDDY_MANGR
    - OVE_ROOTS
    - MULE_SPAWN_EGG
    - MUSHROOM_STEM
    - NETHER_PORTAL
    - OAK_WALL_HANGING_SIGN
    - OAK_WALL_SIGN
    - OCELOT_SPAWN_EGG
    - ORANGE_CANDLE_CAKE
    - ORANGE_WALL_BANNER
    - OXIDIZED_CHISELED_COPPER
    - OXIDIZED_COPPER_BULB
    - OXIDIZED_COPPER_DOOR
    - OXIDIZED_COPPER_GRATE
    - OXIDIZED_COPPER_TRAPDOOR
    - PANDA_SPAWN_EGG
    - PARROT_SPAWN_EGG
    - PETRIFIED_OAK_SLAB
    - PHANTOM_SPAWN_EGG
    - PIG_SPAWN_EGG
    - PIGLIN_BRUTE_SPAWN_EGG
    - PIGLIN_SPAWN_EGG
    - PIGLIN_WALL_HEAD
    - PILLAGER_SPAWN_EGG
    - PINK_CANDLE_CAKE
    - PINK_WALL_BANNER
    - PISTON_HEAD
    - PITCHER_CROP
    - PLAYER_HEAD
    - PLAYER_WALL_HEAD
    - POLAR_BEAR_SPAWN_EGG
    - POTATOES
    - POTION
    - POTTED_ACACIA_SAPLING
    - POTTED_ALLIUM
    - POTTED_AZALEA_BUSH
    - POTTED_AZURE_BLUET
    - POTTED_BAMBOO
    - POTTED_BIRCH_SAPLING
    - POTTED_BLUE_ORCHID
    - POTTED_BROWN_MUSHROOM
    - POTTED_CACTUS
    - POTTED_CHERRY_SAPLING
    - POTTED_CORNFLOWER
    - POTTED_CRIMSON_FUNGUS
    - POTTED_CRIMSON_ROOTS
    - POTTED_DANDELION
    - POTTED_DARK_OAK_SAPLING
    - POTTED_DEAD_BUSH
    - POTTED_FERN
    - POTTED_FLOW
    - ERING_AZALEA_BUSH
    - POTTED_JUNGLE_SAPLING
    - POTTED_LILY_OF_THE_VALLEY
    - POTTED_MANGROVE_PROPAGULE
    - POTTED_OAK_SAPLING
    - POTTED_ORANGE_TULIP
    - POTTED_OXEYE_DAISY
    - POTTED_PINK_TULIP
    - POTTED_POPPY
    - POTTED_RED_MUSHROOM
    - POTTED_RED_TULIP
    - POTTED_SPRUCE_SAPLING
    - POTTED_TORCHFLOWER
    - POTTED_WARPED_FUNGUS
    - POTTED_WARPED_ROOTS
    - POTTED_WHITE_TULIP
    - POTTED_WITHER_ROSE
    - POWDER_SNOW
    - POWDER_SNOW_CAULDRON
    - POWERED_RAIL
    - PUFFERFISH_SPAWN_EGG
    - PUMPKIN_STEM
    - PURPLE_CANDLE_CAKE
    - PURPLE_WALL_BANNER
    - RABBIT_SPAWN_EGG
    - RAVAGER_SPAWN_EGG
    - RED_CANDLE_CAKE
    - RED_WALL_BANNER
    - REDSTONE_WALL_TORCH
    - REDSTONE_WIRE
    - REINFORCED_DEEPSLATE
    - REPEATING_COMMAND_BLOCK
    - SALMON_SPAWN_EGG
    - SHEEP_SPAWN_EGG
    - SHULKER_SPAWN_EGG
    - SILVERFISH_SPAWN_EGG
    - SKELETON_HORSE_SPAWN_EGG
    - SKELETON_SPAWN_EGG
    - SKELETON_WALL_SKULL
    - SLIME_SPAWN_EGG
    - SNIFFER_SPAWN_EGG
    - SNOW
    - SNOW_GOLEM_SPAWN_EGG
    - SOUL_FIRE
    - SOUL_WALL_TORCH
    - SPAWNER
    - SPIDER_SPAWN_EGG
    - SPLASH_POTION
    - SPRUCE_WALL_HANGING_SIGN
    - SPRUCE_WALL_SIGN
    - SQUID_SPAWN_EGG
    - STONE_BRICK_WALL
    - STRAY_SPAWN_EGG
    - STRIDER_SPAWN_EGG
    - STRUCTURE_VOID
    - SUSPICIOUS_GRAVEL
    - SUSPICIOUS_SAND
    - TADPOLE_SPAWN_EGG
    - TALL_GRASS
    - TALL_SEAGRASS
    - TIPPED_ARROW
    - TORCHFLOWER_CROP
    - TRADER_LLAMA_SPAWN_EGG
    - TRIAL_SPAWNER
    - TRIPWIRE
    - TROPICAL_FISH_SPAWN_EGG
    - TUBE_CORAL_WALL_FAN
    - TURTLE_SPAWN_EGG
    - TWISTING_VINES_PLANT
    - VEX_SPAWN_EGG
    - VILLAGER_SPAWN_EGG
    - VINDICATOR_SPAWN_EGG
    - VOID_AIR
    - WALL_TORCH
    - WANDERING_TRADER_SPAWN_EGG
    - WARDEN_SPAWN_EGG
    - WARPED_ROOTS
    - WARPED_WALL_HANGING_SIGN
    - WARPED_WALL_SIGN
    - WATER
    - WATER_CAULDRON
    - WAXED_CHISELED_COPPER
    - WAXED_COPPER_BULB
    - WAXED_COPPER_DOOR
    - WAXED_COPPER_GRATE
    - WAXED_COPPER_TRAPDOOR
    - WAXED_EXPOSED_CHISELED_COPPER
    - WAXED_EXPOSED_COPPER_BULB
    - WAXED_EXPOSED_COPPER_DOOR
    - WAXED_EXPOSED_COPPER_GRATE
    - WAXED_EXPOSED_COPPER_TRAPDOOR
    - WAXED_OXIDIZED_CHISELED_COPPER
    - WAXED_OXIDIZED_COPPER_BULB
    - WAXED_OXIDIZED_COPPER_DOOR
    - WAXED_OXIDIZED_COPPER_GRATE
    - WAXED_OXIDIZED_COPPER_TRAPDOOR
    - WAXED_WEATHERED_CHISELED_COPPER
    - WAXED_WEATHERED_COPPER_BULB
    - WAXED_WEATHERED_COPPER_DOOR
    - WAXED_WEATHERED_COPPER_GRATE
    - WAXED_WEATHERED_COPPER_TRAPDOOR
    - WEATHERED_CHISELED_COPPER
    - WEATHERED_COPPER_BULB
    - WEATHERED_COPPER_DOOR
    - WEATHERED_COPPER_GRATE
    - WEATHERED_COPPER_TRAPDOOR
    - WEEPING_VINES_PLANT
    - WHITE_CANDLE_CAKE
    - WHITE_WALL_BANNER
    - WITCH_SPAWN_EGG
    - WITHER_SKELETON_SPAWN_EGG
    - WITHER_SKELETON_WALL_SKULL
    - WITHER_SPAWN_EGG
    - WOLF_SPAWN_EGG
    - YELLOW_CANDLE_CAKE
    - YELLOW_WALL_BANNER
    - ZOGLIN_SPAWN_EGG
    - ZOMBIE_HORSE_SPAWN_EGG
    - ZOMBIE_SPAWN_EGG
    - ZOMBIE_VILLAGER_SPAWN_EGG
    - ZOMBIE_WALL_HEAD
    - ZOMBIFIED_PIGLIN_SPAWN_EGG