main: de.marylieh.simplebingo.InternalMainClass
name: SimpleBingo
version: 2.0
description: This plugin allows you to play Bingo in Minecraft.
api-version: '1.20'
author: Marylieh

libraries:
  - "net.axay:kspigot:1.20.3"