name: Build Artifacts

on:
  push:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with gradle wrapper
        id: compile
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latest
          path: ./build/libs/