name: Build

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            
            - name: Set up Java
              uses: actions/setup-java@v4
              
              with:
                  java-version: 21
                  distribution: temurin
            
            - name: Gradle (Build)
              uses: gradle/gradle-build-action@v3
              
              with:
                  arguments: build
                  
            - name: Upload artifacts (JARs)
              uses: actions/upload-artifact@v4
              
              with:
                  name: JARs
                  path: build/libs/*.jar